# Generated by Django 2.2.7 on 2020-01-31 09:55

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.IntegerField(db_column='facility_type', unique=True)),
                ('facility_names', models.CharField(db_column='facility_names', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_care', models.IntegerField(db_column='level_of_care', unique=True)),
                ('level_names', models.CharField(db_column='level_names', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField(db_column='location', unique=True)),
                ('location_names', models.CharField(db_column='location_names', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.IntegerField(db_column='program', unique=True)),
                ('program_name', models.CharField(db_column='program_name', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='adelphoi_mapping',
            name='id',
        ),
        migrations.AddField(
            model_name='adelphoi_mapping',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeltests',
            name='condition_program',
            field=models.IntegerField(db_column='condition_program', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='FAST_CaregiverAdvocacyScore',
            field=models.FloatField(blank=True, db_column='FAST_CaregiverAdvocacyScore', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='FAST_FamilyTogetherScore',
            field=models.FloatField(blank=True, db_column='FAST_FamilyTogetherScore', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='Screening_tool_Trauma',
            field=models.FloatField(blank=True, db_column='Screening_tool_Trauma', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='abuse_neglect',
            field=models.FloatField(choices=[(0, 'no'), (1, 'yes')], db_column='abuse_neglect', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='ageAtEnrollStart',
            field=models.IntegerField(db_column='AgeAtEnrollStart', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='ageAtEpisodeStart',
            field=models.IntegerField(db_column='AgeAtEpisodeStart', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='alcohol_Use',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Alcohol_Use', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_CareGiverStrengths',
            field=models.FloatField(blank=True, db_column='CANS_CareGiverStrengths', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_Culture',
            field=models.FloatField(blank=True, db_column='CANS_Culture', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_LifeFunctioning',
            field=models.FloatField(blank=True, db_column='CANS_LifeFunctioning', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_Trauma_Exp',
            field=models.FloatField(blank=True, db_column='CANS_Trauma_Exp', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_YouthBehavior',
            field=models.FloatField(blank=True, db_column='CANS_YouthBehavior', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_YouthRisk',
            field=models.FloatField(blank=True, db_column='CANS_YouthRisk', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='cans_YouthStrengths',
            field=models.FloatField(blank=True, db_column='CANS_YouthStrengths', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='client_self_harm',
            field=models.FloatField(blank=True, db_column='Client_self_harm', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='death_Caregiver',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Death_Caregiver', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='death_Silblings',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Death Silblings', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='drug_Use',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Drug_Use', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='english_second_lang',
            field=models.IntegerField(choices=[(0, 'not at all'), (1, 'very little'), (2, 'average'), (3, 'very well')], db_column='english_second_lang', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='enrollStart_date',
            field=models.DateField(blank=True, db_column='enrollStart_date', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='family_support',
            field=models.FloatField(blank=True, db_column='family_support', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='fire_setting',
            field=models.FloatField(blank=True, db_column='fire_setting', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='incarcerated_siblings',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Incarcerated_siblings', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='level_of_aggression',
            field=models.FloatField(blank=True, db_column='level_of_aggression', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='primaryRaceCode',
            field=models.IntegerField(choices=[(1, 'caucasian'), (2, 'African American'), (3, 'Hispanic'), (4, 'Others')], db_column='PrimaryRacecode', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='referred_program',
            field=models.CharField(choices=[('ISM', 'ISM'), ('ISF', 'ISF'), ('MHFO', 'MHFO'), ('SUBAB', 'SUBAB'), ('DIAGNOSTIC', 'DIAGNOSTIC'), ('SEXOF-MH', 'SEXOF-MH'), ('SEXOF-SECURE', 'SEXOF-SECURE'), ('SEXOF', 'SEXOF'), ('ENHANCED', 'ENHANCED'), ('SECURE-MALE', 'SECURE-MALE'), ('SECURE-FEMALE', 'SECURE-FEMALE'), ('INDEPENDENT LIVING', 'INDEPENDENT LIVING')], db_column='referred_program', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='type_of_drugs',
            field=models.TextField(blank=True, db_column='type_of_drugs', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Attitude_Score',
            field=models.FloatField(blank=True, db_column='YLS_Attitude_Score', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Edu_Employ_Score',
            field=models.FloatField(blank=True, db_column='YLS_Edu_Employ_Score', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_FamCircumstances_Score',
            field=models.FloatField(blank=True, db_column='YLS_FamCircumstances_Score', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Leisure_Score',
            field=models.FloatField(blank=True, db_column='YLS_Leisure_Score', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Peer_Score',
            field=models.FloatField(blank=True, db_column='YLS_Peer_Score', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Personality_Score',
            field=models.FloatField(blank=True, db_column='YLS_Personality_Score', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_PriorCurrentOffenses_Score',
            field=models.FloatField(blank=True, db_column='YLS_PriorCurrentOffenses_Score', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='yls_Subab_Score',
            field=models.FloatField(blank=True, db_column='YLS_Subab_Score', null=True),
        ),
    ]
