# Generated by Django 2.2.7 on 2020-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0003_auto_20200205_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='referred_program',
            field=models.CharField(db_column='referred_program', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
