# Generated by Django 2.2.7 on 2020-02-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0004_auto_20200208_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='incarcerated_caregivers',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], db_column='Incarcerated_caregivers', null=True),
        ),
    ]
