# Generated by Django 2.2.7 on 2020-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0008_auto_20200214_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='adelphoi_mapping',
            name='default_level_facility',
            field=models.BooleanField(db_column='default_level_facility', default=1),
            preserve_default=False,
        ),
    ]
