# Generated by Django 2.2.7 on 2020-02-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0009_adelphoi_mapping_default_level_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='Program_Completion',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Program_Completion', null=True),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='death_Silblings',
            field=models.IntegerField(choices=[(0, 'no'), (1, 'yes')], db_column='Death_Silblings', null=True),
        ),
    ]
