# Generated by Django 2.2.7 on 2020-03-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0010_auto_20200224_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.IntegerField(db_column='referral_code', unique=True)),
                ('referral_name', models.CharField(db_column='referral_name', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='modeltests',
            name='roc_confidence',
            field=models.IntegerField(db_column='roc_confidence', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='CYF_code',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'CYF'), (2, 'Juvenile Justice')], db_column='CYF_code'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='RefSourceCode',
            field=models.IntegerField(db_column='RefSourceCode'),
        ),
        migrations.AlterField(
            model_name='modeltests',
            name='ls_type',
            field=models.IntegerField(choices=[(1, 'voluntary'), (2, 'Dependent'), (5, 'Delinquent')], db_column='LS_Type'),
        ),
    ]
