# Generated by Django 2.2.7 on 2020-03-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0011_auto_20200303_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='referred_program',
            field=models.CharField(choices=[('ISM', 'ISM'), ('ISF', 'ISF'), ('MHFO', 'MHFO'), ('SUBAB', 'SUBAB'), ('SEXOF-MH', 'SEXOF-MH'), ('SEXOF-SECURE', 'SEXOF-SECURE'), ('SEXOF', 'SEXOF'), ('SECURE-MALE', 'SECURE-MALE'), ('SECURE-FEMALE', 'SECURE-FEMALE'), ('INDEPENDENT LIVING', 'Independent Living'), ('Transitional Living', 'Transitional Living')], db_column='referred_program', max_length=100, null=True),
        ),
    ]
