# Generated by Django 2.2.12 on 2020-05-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstMatch', '0013_auto_20200430_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltests',
            name='roc_confidence',
            field=models.IntegerField(blank=True, db_column='roc_confidence', null=True),
        ),
    ]
